version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/share/nginx/html
    depends_on:
      - api

  api:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./src:/app
    command: npm start
    environment:
      - NODE_ENV=development
    ports:
      - "8080:8080"

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: drvital
      POSTGRES_USER: drvital
      POSTGRES_PASSWORD: drvital
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: 