name: Deploy DrVital to GitHub Pages

on:
  # Trigger on push to drvital-main branch
  push:
    branches: [ drvital-main ]
  # Allow manual trigger
  workflow_dispatch:

# Required permissions for GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Prevent concurrent deployments
concurrency:
  group: "drvital-pages"
  cancel-in-progress: false

# Environment configuration
env:
  GITHUB_PAGES_BRANCH: drvital-gh-pages  # Branch for GitHub Pages
  GITHUB_PAGES_FOLDER: drvital-custom/public  # Source folder

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: drvital-main  # Use our DrVital branch
      
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3
        with:
          enablement: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build with Docker
        run: |
          cd drvital-custom
          docker compose up -d
          sleep 30  # Wait for services to start
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ env.GITHUB_PAGES_FOLDER }}

  deploy:
    environment:
      name: drvital-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ env.GITHUB_PAGES_FOLDER }} 